#pragma once

#ifndef _LIBCUDAFORDALICXX_NO_EXCEPTIONS
#define _LIBCUDAFORDALICXX_TEST_TRY try
#define _LIBCUDAFORDALICXX_TEST_CATCH(...) catch(__VA_ARGS__)
#else
#define _LIBCUDAFORDALICXX_TEST_TRY if (1)
#define _LIBCUDAFORDALICXX_TEST_CATCH(...) else if (0)
#endif // _LIBCUDAFORDALICXX_NO_EXCEPTIONS
